version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Sao_Paulo"

    open-pull-requests-limit: 5

    groups:
      dev-dependencies:
        dependency-type: "development"
      production-dependencies:
        dependency-type: "production"

    commit-message:
      prefix: "deps"
      include: "scope"

    labels:
      - "dependencies"
      - "bot"

    reviewers:
      - "mkafonso"

    ignore:
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
